name: Build/Deploy on Push

on:
  push:
    branches:
      - master

jobs:
  run:
    name: Build/Deploy on Push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm install

      - run: npm run build
      - run: npm test
        timeout-minutes: 1
